# Generated by Django 5.0.6 on 2024-05-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suplency', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlashCardMateria',
            new_name='FlashCard_Materia',
        ),
    ]
