# Generated by Django 5.0.4 on 2024-07-20 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('suplency', '0002_remove_pomodoro_nome_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagina',
            options={'ordering': ['numero_da_pagina']},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ultima_materia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ultima_pagina',
        ),
        migrations.AlterField(
            model_name='pagina',
            name='conteudo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='cor_da_folha',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='usuarios', related_query_name='usuario', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='permissoes',
            field=models.ManyToManyField(blank=True, related_name='usuarios', related_query_name='usuario', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='Informacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_ultima_materia', to='suplency.materia')),
                ('ultima_pagina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_ultima_pagina', to='suplency.pagina')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
