# Generated by Django 5.0.6 on 2024-05-23 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplency', '0002_rename_flashcardmateria_flashcard_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultima_materia', to='suplency.materia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_pagina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultima_pagina', to='suplency.pagina'),
        ),
    ]
