# Generated by Django 5.0.4 on 2024-07-20 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplency', '0004_alter_materia_cor_da_materia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caderno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_ultima_materia', to='suplency.materia')),
                ('ultima_pagina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_ultima_pagina', to='suplency.pagina')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caderno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='materia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia', to='suplency.caderno'),
        ),
        migrations.DeleteModel(
            name='Informacoes',
        ),
    ]
