# Generated by Django 5.0.4 on 2024-07-20 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplency', '0005_caderno_alter_materia_usuario_delete_informacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flashcardmateria',
            name='flash_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_materia', to='suplency.flashcard'),
        ),
        migrations.AlterField(
            model_name='flashcardmateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_materia', to='suplency.materia'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagina', to='suplency.materia'),
        ),
    ]
