# Generated by Django 5.0.4 on 2024-07-20 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplency', '0006_alter_flashcard_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagina',
            options={'ordering': ['numero_pagina']},
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='usuario',
            new_name='caderno',
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='numero_da_pagina',
            new_name='numero_pagina',
        ),
        migrations.RemoveField(
            model_name='caderno',
            name='ultima_pagina',
        ),
        migrations.AddField(
            model_name='materia',
            name='ultima_pagina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultima_materia', to='suplency.pagina'),
        ),
        migrations.AlterField(
            model_name='caderno',
            name='ultima_materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultima_materia', to='suplency.materia'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nome_da_materia',
            field=models.CharField(default='Nova matéria', max_length=32),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='conteudo',
            field=models.TextField(default='<p></p>'),
        ),
    ]
