# Generated by Django 5.0.4 on 2024-07-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suplency', '0007_alter_pagina_options_rename_usuario_materia_caderno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagina',
            options={'ordering': ['numero']},
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='cor_da_materia',
            new_name='cor',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='nome_da_materia',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='cor_da_folha',
            new_name='cor',
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='numero_pagina',
            new_name='numero',
        ),
    ]
