# Generated by Django 5.0.4 on 2024-07-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplency', '0008_alter_pagina_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='cor',
            field=models.CharField(default='white', max_length=32),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='cor',
            field=models.CharField(default='white', max_length=32),
        ),
    ]
