# Generated by Django 5.0.4 on 2024-07-27 22:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplency', '0009_alter_materia_cor_alter_pagina_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
